const BlogData = [
  {
    id: 1,
    data: "january 01, 2024",
    catgeory: "Business",
    title: "The Most Advance Business Plan",
    cover: "/images/blog-1.jpg",
    para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
  },
  {
    id: 2,
    data: "january 15, 2023",
    catgeory: "Traveling",
    title: "Beautiful Home Page",
    cover: "/images/blog-2.jpg",
    para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
  },
  {
    id: 3,
    data: "january 21, 2022",
    catgeory: "Development",
    title: "Modern Design Concept",
    cover: "/images/blog-3.jpg",
    para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
  },
  {
    id: 4,
    data: "january 30, 2019",
    catgeory: "Motion Designer",
    title: "Smart Flexible Visiting Card",
    cover: "/images/blog-3.jpg",
    para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
  },
  {
    id: 5,
    data: "january 10, 2024",
    catgeory: "Content Writing",
    title: "Investment plannig",
    cover: "/images/blog-5.jpg",
    para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
  },
  {
    id: 6,
    data: "january 18, 2022",
    catgeory: "Web Development",
    title: "Why You Should Always First",
    cover: "/images/blog-2.jpg",
    para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
  },
  {
    id: 7,
    data: "january 23, 2024",
    catgeory: "Business Strategy",
    title: "Investment Planning",
    cover: "/images/blog-1.jpg",
    para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
  },
  {
    id: 8,
    data: "january 30, 2019",
    catgeory: "Motion Designer",
    title: "Smart Flexible Visiting Card",
    cover: "/images/blog-3.jpg",
    para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
  },
  {
    id: 9,
    data: "january 10, 2022",
    catgeory: "Content Writing",
    title: "Investment Planning",
    cover: "/images/blog-5.jpg",
    para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligend  necessitatibus quam quis amet temporibus, obcaecati at tempora, officiis repudiandae eius dolorum magnam tenetur placeat laboriosam   facilis sapiente ut. Adipisci, dolor.",
  },
];

export default BlogData;
